import time
import os


class Cell:
    def __init__(self, state):
        self.state = state
        self.neighbors = 0

    def update(self):
        self.state = self.neighbors == 3 or self.state and self.neighbors == 2
        self.neighbors = 0

    def __str__(self):
        return "██" if self.state else "░░"


class Board:
    def __init__(self, initial):
        lines = initial.strip().splitlines()

        self.cells = []
        self.height = len(lines)
        self.width = len(lines[0])

        for line in lines:
            assert len(line) == self.width
            row = [Cell(sym != ".") for sym in line]
            self.cells.append(row)

    def get_state(self, r, c):
        if r < 0 or r >= self.height or c < 0 or c >= self.width:
            return False

        return self.cells[r][c].state

    def update(self):
        for r in range(self.height):
            for c in range(self.width):
                self.sum_neighbors(r, c)

        for row in self.cells:
            for cell in row:
                cell.update()

    def sum_neighbors(self, r, c):
        cell = self.cells[r][c]

        for dr in [-1, 0, 1]:
            for dc in [-1, 0, 1]:
                if dr or dc:
                    cell.neighbors += self.get_state(r + dr, c + dc)

    def __str__(self):
        return "\n".join("".join(str(cell) for cell in row) for row in self.cells)


blinker = """
.....
..#..
..#..
..#..
.....
"""

loaf = """
......
..##..
.#..#.
..#.#.
...#..
......
"""

glider = """
.......
..#....
...#...
.###...
.......
.......
.......
"""

octagon2 = """
..........
....##....
...#..#...
..#....#..
.#......#.
.#......#.
..#....#..
...#..#...
....##....
..........
"""

rpentomino = """
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
...................##...................
..................##....................
...................#....................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
"""

board = Board(blinker)

for generation in range(500):
    os.system("clear")
    print(board)
    print(f"generation: {generation}")
    time.sleep(0.2)
    board.update()
